### ISSUE TITLE
Page not found (404) error

### ISSUE THREAD

**Issue by madrisan** [FataPlex/documentation#1]
The link in the `README.md`, https://github.com/FataPlex/documentation/blob/master/lvm
is broken.
Should be https://github.com/FataPlex/documentation/blob/master/lvm.md

**Comment by baptiste-dauphin** [comment]
I didn't see. Thanks @madrisan 

https://github.com/FataPlex/documentation/commit/9ff84b6b5b1ea40603a2af1e36b4445f9ec6b710
